apiVersion: v1
kind: Service

metadata:
  name: react-cicd-service

spec:

  selector:
    app: react-cicd

  type: NodePort

  ports:

  - protocol: TCP

    port: 80

    targetPort: 80

    nodePort: 30080